### ISSUE TITLE
"/faculty" route doesnt give any data

### ISSUE THREAD

**Issue by TheR3dWizard** [akashShanmugraj/psgscapes-production-server#5]
![image](https://user-images.githubusercontent.com/34707235/235345237-df929d02-5805-4012-8548-eb40b9fdd24f.png)

**Comment by akashShanmugraj** [comment]
@TheR3dWizard Currently the database does not have any sample data of faculty members. 
You can request for **one** sample data entry

**Comment by aknsubbu** [comment]
Fixed
